/*
  # Create Update Content Function

  1. Purpose
    - Create a stored procedure to update timeless_content
    - Bypasses PostgREST schema cache issues
    - Handles both insert and update operations
  
  2. Function
    - `update_timeless_content()` - Updates or inserts content with all fields
*/

-- Create or replace function to update timeless content
CREATE OR REPLACE FUNCTION update_timeless_content(
  p_id uuid,
  p_couple_names text DEFAULT '',
  p_groom_full_name text DEFAULT '',
  p_bride_full_name text DEFAULT '',
  p_wedding_title text DEFAULT '',
  p_wedding_date text DEFAULT '',
  p_venue_name text DEFAULT '',
  p_venue_address text DEFAULT '',
  p_venue_maps text DEFAULT '',
  p_ceremony_time text DEFAULT '',
  p_reception_time text DEFAULT '',
  p_background_image text DEFAULT '',
  p_groom_photo text DEFAULT '',
  p_bride_photo text DEFAULT '',
  p_thank_you_message text DEFAULT '',
  p_hero_title text DEFAULT '',
  p_hero_image text DEFAULT '',
  p_hero_background_image text DEFAULT NULL,
  p_livestreaming_image text DEFAULT NULL,
  p_background_section_1 text DEFAULT '',
  p_background_section_1_size text DEFAULT 'cover',
  p_background_section_1_position text DEFAULT 'center center',
  p_background_section_2 text DEFAULT '',
  p_background_section_2_size text DEFAULT 'cover',
  p_background_section_2_position text DEFAULT 'center center',
  p_background_section_3 text DEFAULT '',
  p_background_section_3_size text DEFAULT 'cover',
  p_background_section_3_position text DEFAULT 'center center',
  p_background_section_4 text DEFAULT '',
  p_background_section_4_size text DEFAULT 'cover',
  p_background_section_4_position text DEFAULT 'center center',
  p_background_section_5 text DEFAULT '',
  p_background_section_5_size text DEFAULT 'cover',
  p_background_section_5_position text DEFAULT 'center center',
  p_gallery_images jsonb DEFAULT '[]'::jsonb,
  p_price numeric(10, 2) DEFAULT 0,
  p_template_name text DEFAULT 'timeless',
  p_slug text DEFAULT '',
  p_status text DEFAULT 'draft',
  p_password_protected boolean DEFAULT false,
  p_invitation_password text DEFAULT '',
  p_is_published boolean DEFAULT false
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Update or insert
  INSERT INTO timeless_content (
    id,
    couple_names,
    groom_full_name,
    bride_full_name,
    wedding_title,
    wedding_date,
    venue_name,
    venue_address,
    venue_maps,
    ceremony_time,
    reception_time,
    background_image,
    groom_photo,
    bride_photo,
    thank_you_message,
    hero_title,
    hero_image,
    hero_background_image,
    livestreaming_image,
    background_section_1,
    background_section_1_size,
    background_section_1_position,
    background_section_2,
    background_section_2_size,
    background_section_2_position,
    background_section_3,
    background_section_3_size,
    background_section_3_position,
    background_section_4,
    background_section_4_size,
    background_section_4_position,
    background_section_5,
    background_section_5_size,
    background_section_5_position,
    gallery_images,
    price,
    template_name,
    slug,
    status,
    password_protected,
    invitation_password,
    is_published,
    updated_at
  ) VALUES (
    COALESCE(p_id, gen_random_uuid()),
    p_couple_names,
    p_groom_full_name,
    p_bride_full_name,
    p_wedding_title,
    p_wedding_date,
    p_venue_name,
    p_venue_address,
    p_venue_maps,
    p_ceremony_time,
    p_reception_time,
    p_background_image,
    p_groom_photo,
    p_bride_photo,
    p_thank_you_message,
    p_hero_title,
    p_hero_image,
    p_hero_background_image,
    p_livestreaming_image,
    p_background_section_1,
    p_background_section_1_size,
    p_background_section_1_position,
    p_background_section_2,
    p_background_section_2_size,
    p_background_section_2_position,
    p_background_section_3,
    p_background_section_3_size,
    p_background_section_3_position,
    p_background_section_4,
    p_background_section_4_size,
    p_background_section_4_position,
    p_background_section_5,
    p_background_section_5_size,
    p_background_section_5_position,
    p_gallery_images,
    p_price,
    p_template_name,
    p_slug,
    p_status,
    p_password_protected,
    p_invitation_password,
    p_is_published,
    now()
  )
  ON CONFLICT (id) DO UPDATE SET
    couple_names = EXCLUDED.couple_names,
    groom_full_name = EXCLUDED.groom_full_name,
    bride_full_name = EXCLUDED.bride_full_name,
    wedding_title = EXCLUDED.wedding_title,
    wedding_date = EXCLUDED.wedding_date,
    venue_name = EXCLUDED.venue_name,
    venue_address = EXCLUDED.venue_address,
    venue_maps = EXCLUDED.venue_maps,
    ceremony_time = EXCLUDED.ceremony_time,
    reception_time = EXCLUDED.reception_time,
    background_image = EXCLUDED.background_image,
    groom_photo = EXCLUDED.groom_photo,
    bride_photo = EXCLUDED.bride_photo,
    thank_you_message = EXCLUDED.thank_you_message,
    hero_title = EXCLUDED.hero_title,
    hero_image = EXCLUDED.hero_image,
    hero_background_image = EXCLUDED.hero_background_image,
    livestreaming_image = EXCLUDED.livestreaming_image,
    background_section_1 = EXCLUDED.background_section_1,
    background_section_1_size = EXCLUDED.background_section_1_size,
    background_section_1_position = EXCLUDED.background_section_1_position,
    background_section_2 = EXCLUDED.background_section_2,
    background_section_2_size = EXCLUDED.background_section_2_size,
    background_section_2_position = EXCLUDED.background_section_2_position,
    background_section_3 = EXCLUDED.background_section_3,
    background_section_3_size = EXCLUDED.background_section_3_size,
    background_section_3_position = EXCLUDED.background_section_3_position,
    background_section_4 = EXCLUDED.background_section_4,
    background_section_4_size = EXCLUDED.background_section_4_size,
    background_section_4_position = EXCLUDED.background_section_4_position,
    background_section_5 = EXCLUDED.background_section_5,
    background_section_5_size = EXCLUDED.background_section_5_size,
    background_section_5_position = EXCLUDED.background_section_5_position,
    gallery_images = EXCLUDED.gallery_images,
    price = EXCLUDED.price,
    template_name = EXCLUDED.template_name,
    slug = EXCLUDED.slug,
    status = EXCLUDED.status,
    password_protected = EXCLUDED.password_protected,
    invitation_password = EXCLUDED.invitation_password,
    is_published = EXCLUDED.is_published,
    updated_at = now()
  RETURNING id INTO p_id;

  RETURN p_id;
END;
$$;